import { SuccessStory } from "./types";

export const SUCCESS_STORIES: SuccessStory[] = [
  {
    id: "story-1",
    patientName: "Sarah Jenkins",
    country: "United Kingdom",
    flag: "/flags/United Kingdom (GB).jpg",
    condition: "Severe Rheumatoid Arthritis",
    quote: "I arrived in a wheelchair and walked out 28 days later. The healing here is profound.",
    before: "Suffered from debilitating joint pain for over 5 years. Unable to perform basic daily tasks and heavily dependent on painkillers.",
    after: "Mobility completely restored. Pain-free and medication-free following a 28-day intensive Panchakarma and specialized Kizhi treatment protocol.",
    hasVideo: true,
    video: "/ayurveda-mana-videos/001 Ayurvedhamana.mp4",
    coverPhoto: "/hero-bg/client-tratment.png",
  },
  {
    id: "story-2",
    patientName: "Markus Weber",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Chronic Migraine & Stress",
    quote: "The Shirodhara treatments rewired my nervous system. I finally have my life back.",
    before: "Experienced severe migraines 3-4 times a week, compounded by chronic insomnia and executive burnout.",
    after: "Zero migraine episodes since completing the 14-day Stress Management package. Sleep architecture completely normalized.",
    hasVideo: false,
  },
  {
    id: "story-3",
    patientName: "Fatima Al-Sayed",
    country: "United Arab Emirates",
    flag: "/flags/United Arab Emirates (AE).jpg",
    condition: "Obesity & Metabolic Syndrome",
    quote: "The doctors here didn't just treat my symptoms; they completely reset my metabolism. The care, the diet, and the treatments were phenomenal.",
    hasVideo: false,
  },
  {
    id: "story-4",
    patientName: "David Chen",
    country: "United Kingdom",
    flag: "/flags/United Kingdom (GB).jpg",
    condition: "Lumbar Disc Prolapse (Sciatica)",
    before: "Severe radiating pain down the left leg. Scheduled for spinal surgery in Singapore.",
    after: "95% pain reduction. Avoided surgery entirely after targeted Kati Vasti and Chavitti Uzhichil therapies.",
    hasVideo: true,
    video: "/ayurveda-mana-videos/LIFE STYLE DISEASE MANAGMENT  MOB.mp4",
    coverPhoto: "/hero-bg/client-oilmessage.png",
  },
  {
    id: "story-5",
    patientName: "Elena Rostova",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Psoriasis",
    hasVideo: true,
    video: "/ayurveda-mana-videos/ANTI  AGING TREATMENT MOB.mp4",
    coverPhoto: "/hero-bg/clent-yoga.png",
  },
  {
    id: "story-6",
    patientName: "Michael Carter",
    country: "United Kingdom",
    flag: "/flags/United Kingdom (GB).jpg",
    condition: "Chronic Lower Back Pain (L4-L5 Spondylosis)",
    quote: "The targeted Basti treatments and specialized massages restored my spine health completely. I feel ten years younger.",
    before: "Suffered from constant lower back stiffness and sharp nerve pain for three years. Limited sitting and walking endurance.",
    after: "Spinal mobility restored and pain completely resolved after a 21-day treatment series of Kati Vasti and Elakizhi.",
    hasVideo: true,
    video: "/ayurveda-mana-videos/YOGA AND MEDITATION MOB.mp4",
    coverPhoto: "/hero-bg/client-food.png",
  },
  {
    id: "story-7",
    patientName: "Emily Dupoint",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Anxiety & Burnout Syndrome",
    quote: "A peaceful sanctuary that brought back my mental clarity. The therapeutic oil treatments re-anchored my nervous system.",
    before: "Struggled with severe mental exhaustion, chronic insomnia, palpitations, and inability to focus due to executive burnout.",
    after: "Sleep quality normalized. Experienced deep mental stillness, physical rejuvenation, and normalized heart rate after a 14-day Manasanthi package.",
    hasVideo: false,
  },
  {
    id: "story-8",
    patientName: "Robert Hughes",
    country: "United Arab Emirates",
    flag: "/flags/United Arab Emirates (AE).jpg",
    condition: "Knee Osteoarthritis",
    quote: "The herbal poultices and Janu Basti therapy did wonders for my knees. I can walk long distances pain-free now.",
    before: "Severe joint space narrowing in both knees. Experienced crepitus, swelling, and acute pain when climbing stairs.",
    after: "Significant reduction in swelling and stiffness. Walking range increased to 5km comfortably after a 28-day knee rejuvenation protocol.",
    hasVideo: false,
  },
  {
    id: "story-9",
    patientName: "Chantal Laurent",
    country: "United Kingdom",
    flag: "/flags/United Kingdom (GB).jpg",
    condition: "Irritable Bowel Syndrome (IBS)",
    quote: "Ayurvedic diet, customized herbs, and cleansing treatments resolved years of bloating and abdominal discomfort.",
    before: "Faced chronic indigestion, erratic bowel movements, severe abdominal pain, and multiple food intolerances.",
    after: "Digestion reset completely. Reintroduced regular foods into diet without reaction following a 21-day Virechana purification therapy.",
    hasVideo: false,
  },
  {
    id: "story-10",
    patientName: "Andreas Meier",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Fibromyalgia & Fatigue",
    quote: "Gentle oil massages, tailored herbs, and holistic care reduced my chronic muscular pain and fatigue significantly.",
    before: "Widespread muscle tenderness, brain fog, and muscle weakness. Highly sensitive to external stimuli.",
    after: "Achieved 80% reduction in muscle pain points. Sleep and daily energy levels improved dramatically over a 21-day wellness cycle.",
    hasVideo: false,
  },
  {
    id: "story-11",
    patientName: "Ramesh Krishnan",
    country: "United Arab Emirates",
    flag: "/flags/United Arab Emirates (AE).jpg",
    condition: "Psoriatic Arthritis",
    quote: "Panchakarma detox brought lasting relief when standard immunosuppressive medicines failed.",
    before: "Red scaly skin patches on limbs accompanied by severe joint inflammation, swelling, and pain in fingers and toes.",
    after: "Skin cleared up by 90% and joint inflammation vanished. Discharged pain-free after completing a 28-day intensive detoxification therapy.",
    hasVideo: false,
  },
  {
    id: "story-12",
    patientName: "Kenji Sato",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Chronic Fatigue Syndrome",
    quote: "Rejuvenating therapies, organic herbs, and a structured diet restored my physical energy levels completely.",
    before: "Extreme fatigue unmitigated by rest, muscle aches, and zero stamina for basic tasks.",
    after: "Stamina and vigor fully restored. Returned to normal active lifestyle after a 14-day Rasayana rejuvenation treatment.",
    hasVideo: false,
  },
  {
    id: "story-13",
    patientName: "Rajesh Kumar",
    country: "United Arab Emirates",
    flag: "/flags/United Arab Emirates (AE).jpg",
    condition: "Type-2 Diabetes Management",
    quote: "Personalized diet, yoga, and natural herbal formulations naturally stabilized my blood sugar levels.",
    before: "Uncontrolled blood sugar levels (HbA1c of 8.5) and high dependence on oral diabetic medications.",
    after: "HbA1c level reduced to 6.2. Medication dosage safely lowered under medical supervision after a 21-day purification protocol.",
    hasVideo: true,
    video: "/ayurveda-mana-videos/TREATMENT FOR OBESITY MOB.mp4",
    coverPhoto: "/hero-bg/client-tratment.png",
  },
  {
    id: "story-14",
    patientName: "Johan Botha",
    country: "United Kingdom",
    flag: "/flags/United Kingdom (GB).jpg",
    condition: "Insomnia & Sleep Apnea",
    quote: "Shirodhara and herbal steam treatments completely re-established my natural circadian sleep cycle.",
    before: "Dependent on sleeping pills for over four years. Experienced constant daytime drowsiness and morning headaches.",
    after: "Able to fall asleep naturally without medication. Morning grogginess and sleep apnea symptoms resolved after a 14-day therapy.",
    hasVideo: false,
  },
  {
    id: "story-15",
    patientName: "Sven Johansson",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Asthma & Respiratory Allergies",
    quote: "Therapeutic Nasyam and herbal steam treatments opened my congested airways fully.",
    before: "Sufferer of chronic shortness of breath, wheezing, and seasonal sinus congestions requiring daily inhalers.",
    after: "Respiratory capacity improved, inhaler dependency eliminated after a 21-day breathing rejuvenation and cleansing therapy.",
    hasVideo: false,
  },
  {
    id: "story-16",
    patientName: "Giovanni Rossi",
    country: "United Arab Emirates",
    flag: "/flags/United Arab Emirates (AE).jpg",
    condition: "Hypertension",
    quote: "Daily meditation, organic diet, and detoxification therapies safely normalized my blood pressure.",
    before: "High blood pressure (160/95 mmHg) linked to lifestyle stress. Experienced frequent dizziness.",
    after: "Blood pressure stabilized at 125/80 mmHg naturally. Left feeling peaceful and re-centered after 14 days of therapies.",
    hasVideo: false,
  },
  {
    id: "story-17",
    patientName: "Maria Garcia",
    country: "United Kingdom",
    flag: "/flags/United Kingdom (GB).jpg",
    condition: "Chronic Eczema",
    quote: "Blood purifying herbs and soothing oils healed my itchy skin from the inside out.",
    before: "Intense itching, dry cracked skin, and bleeding lesions on elbows and neck for several years.",
    after: "Complete healing of skin lesions and cessation of itching after a 21-day blood purification (Raktamokshana) protocol.",
    hasVideo: false,
  },
  {
    id: "story-18",
    patientName: "Willem van den Berg",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Sciatica & Piriformis Syndrome",
    quote: "Kati Vasti therapy completely relieved the radiating nerve pain down my right leg.",
    before: "Excruciating pain radiating from the hip to the heel, making walking or standing for more than 5 minutes impossible.",
    after: "Pain free. Spinal flexibility and posture normalized after 21 days of target hot oil pooling and herbal leaf bag massage.",
    hasVideo: false,
  },
  {
    id: "story-19",
    patientName: "Astrid Larsen",
    country: "United Arab Emirates",
    flag: "/flags/United Arab Emirates (AE).jpg",
    condition: "Cervical Spondylosis",
    quote: "Spinal rejuvenation treatments restored my neck and shoulder mobility completely.",
    before: "Severe neck stiffness, radiating numbness in right arm, and chronic tension headaches.",
    after: "Numbness disappeared and full neck rotation restored after 14 days of Greeva Vasti and Pizhichil treatments.",
    hasVideo: false,
  },
  {
    id: "story-20",
    patientName: "Liam Williams",
    country: "United Kingdom",
    flag: "/flags/United Kingdom (GB).jpg",
    condition: "Stress Burnout & Fatigue",
    quote: "The calm environment, dedicated doctors, and organic diet reset my entire life.",
    before: "Felt chronically depleted of energy, suffering from frequent tension headaches and digestive upsets.",
    after: "Full vitality restored. Digestion normalized and headache-free after 14 days of organic herbal therapies and wellness routine.",
    hasVideo: true,
    video: "/ayurveda-mana-videos/SLEEP DISORDER MOB.mp4",
    coverPhoto: "/hero-bg/client-oilmessage.png",
  },
  {
    id: "story-21",
    patientName: "Fiona O'Connor",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Gouty Arthritis",
    quote: "Herbal decoctions cleared the swelling and sharp pain in my joints.",
    before: "Recurrent attacks of acute pain, redness, and swelling in the big toe and ankles due to high uric acid.",
    after: "Uric acid levels normalized and joint inflammation resolved after a 21-day custom detoxification protocol.",
    hasVideo: false,
  },
  {
    id: "story-22",
    patientName: "Camila Silva",
    country: "United Arab Emirates",
    flag: "/flags/United Arab Emirates (AE).jpg",
    condition: "Hypothyroidism & Slow Metabolism",
    quote: "Holistic herbal remedies corrected my hormonal imbalance and metabolic rate naturally.",
    before: "Faced rapid weight gain, extreme lethargy, dry skin, and hair loss due to underactive thyroid.",
    after: "Metabolism normalized, lost excess weight, and thyroid hormone levels stabilized after 21 days of Udvarthanam therapy.",
    hasVideo: false,
  },
  {
    id: "story-23",
    patientName: "Thomas Wagner",
    country: "United Kingdom",
    flag: "/flags/United Kingdom (GB).jpg",
    condition: "Chronic Sinusitis",
    quote: "Therapeutic Nasyam treatment relieved my chronic nasal congestion and headaches.",
    before: "Suffered from daily facial pressure, chronic nasal blockage, loss of smell, and frequent headaches.",
    after: "Sinus cavities completely cleared, breathing normalized, and sense of smell returned after a 14-day Nasyam protocol.",
    hasVideo: false,
  },
  {
    id: "story-24",
    patientName: "Mette Nielsen",
    country: "Germany",
    flag: "/flags/Germany (DE).jpg",
    condition: "Post-Stroke Rehabilitation",
    quote: "Consistent oil massages and herbal steam helped restore my muscle strength and motor coordination.",
    before: "Faced weakness on the left side of the body, slurred speech, and unsteady gait post-stroke.",
    after: "Significant improvement in muscle tone, walking stability, and speech clarity after 28 days of targeted Navarakizhi therapy.",
    hasVideo: false,
  },
  {
    id: "story-25",
    patientName: "Lucas Devolder",
    country: "United Arab Emirates",
    flag: "/flags/United Arab Emirates (AE).jpg",
    condition: "Peripheral Neuropathy",
    quote: "Nourishing Ayurvedic treatments restored normal sensation to my hands and feet.",
    before: "Experienced burning, tingling, and numbness in limbs, especially at night. Disturbed sleep.",
    after: "Burning sensation ceased and normal tactile sensation returned after 21 days of milk-boiled herbal rice bag massage.",
    hasVideo: false,
  }
];
